name: Adam Davis
favicon: null
layout_spectrum: 1
typography_spectrum: 0.27499
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3387a6'
    - '#eef3f7'
    - '#3f5d90'
    - '#b8ccda'
    - '#7ba4bc'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.3083454421721399
  rhythmicContrast: 1
purpose: []
