name: Adam Davis
favicon: null
layout_spectrum: 1
typography_spectrum: 0.27499
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.625
  lightness: 0.3394267400726676
  saturation: 0.3083454421721399
  rhythmicContrast: 0.2882244526408613
purpose: []
